export const PATHS = {
  ROOT: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  ONBOARDING: '/onboarding',
  DASHBOARD: '/dashboard',
  ROADMAP: '/roadmap',
  OPPORTUNITIES: '/opportunities',
  SAVED: '/opportunities/saved',
  opportunityDetail: (id) => `/opportunities/${id}`,
  SKILLS: '/skills',
  AI_STUDIO: '/ai-studio',
  ACHIEVEMENTS: '/achievements',
  PROFILE: '/profile',
  ORGANIZATION: '/organization',
  ORGANIZATION_PROFILE: '/organization/profile',
  ORGANIZATION_MEMBERS: '/organization/members',
  ORGANIZATION_OPPORTUNITIES: '/organization/opportunities',
  ORGANIZATION_OPPORTUNITY_NEW: '/organization/opportunities/new',
  organizationOpportunity: (id) => `/organization/opportunities/${id}`,
  organizationOpportunityEdit: (id) => `/organization/opportunities/${id}/edit`,
  ADMIN: '/admin',
  ADMIN_OPPORTUNITIES: '/admin/opportunities',
  ADMIN_OPPORTUNITY_NEW: '/admin/opportunities/new',
  adminOpportunity: (id) => `/admin/opportunities/${id}`,
  adminOpportunityEdit: (id) => `/admin/opportunities/${id}/edit`,
  ADMIN_ORGANIZATIONS: '/admin/organizations',
  ADMIN_CAREER_PATH_REQUESTS: '/admin/career-path-requests',
  ADMIN_ROADMAPS: '/admin/roadmaps',
  adminRoadmap: (id) => `/admin/roadmaps/${id}`,
  adminRoadmapPreview: (id) => `/admin/roadmaps/${id}/preview`,
  adminRoadmapStepNew: (id) => `/admin/roadmaps/${id}/steps/new`,
  adminRoadmapStepEdit: (pathId, stepId) => `/admin/roadmaps/${pathId}/steps/${stepId}/edit`,
  ADMIN_USERS: '/admin/users',
  adminUser: (id) => `/admin/users/${id}`,
  ADMIN_SUBSCRIPTIONS: '/admin/subscriptions',
  adminSubscription: (id) => `/admin/subscriptions/${id}`,
}

export const TOKEN_KEY = 'pathforge_token'
